import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';

export default defineConfig(({ mode }) => {
  // Load .env.dfx (generated by dfx deploy) alongside regular env files
  const env = loadEnv(mode, process.cwd(), '');

  const network = env.DFX_NETWORK ?? 'local';
  const isLocal = network !== 'ic';

  return {
    plugins: [react(), tailwindcss()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        '@core': path.resolve(__dirname, './src/core'),
        '@features': path.resolve(__dirname, './src/features'),
        '@ui': path.resolve(__dirname, './src/ui'),
        '@entities': path.resolve(__dirname, './src/entities'),
        '@hooks': path.resolve(__dirname, './src/hooks'),
        '@utils': path.resolve(__dirname, './src/utils'),
        '@types': path.resolve(__dirname, './src/types'),
        '@constants': path.resolve(__dirname, './src/constants'),
      },
    },
    define: {
      // Inject ICP canister IDs at build time from .env.dfx
      'process.env.CANISTER_ID_LAND_NFT': JSON.stringify(env.CANISTER_ID_LAND_NFT ?? ''),
      'process.env.CANISTER_ID_FRONTIER_TOKEN': JSON.stringify(env.CANISTER_ID_FRONTIER_TOKEN ?? ''),
      'process.env.CANISTER_ID_GAME_STATE': JSON.stringify(env.CANISTER_ID_GAME_STATE ?? ''),
      'process.env.CANISTER_ID_INTERNET_IDENTITY': JSON.stringify(
        isLocal ? (env.CANISTER_ID_INTERNET_IDENTITY ?? '') : 'rdmx6-jaaaa-aaaaa-aaadq-cai'
      ),
      'process.env.DFX_NETWORK': JSON.stringify(network),
    },
    build: {
      target: 'es2020',
      sourcemap: true,
      rollupOptions: {
        output: {
          manualChunks(id: string) {
            if (id.includes('node_modules/three/')) return 'three';
            if (id.includes('node_modules/@react-three/')) return 'r3f';
            if (id.includes('node_modules/@dfinity/')) return 'dfinity';
          },
        },
      },
    },
    server: {
      host: true,
      port: 5173,
      // Proxy /api requests to local ICP replica during development
      proxy: isLocal
        ? {
            '/api': {
              target: 'http://127.0.0.1:4943',
              changeOrigin: true,
            },
          }
        : undefined,
    },
  };
});
